### ISSUE TITLE
Recomendación

### ISSUE THREAD

**Issue by fernaper** [luck5941/curriculum#1]
Buenas Lucas, he visto el CV y como recomendación (por lo que he visto en el mercado), quizá queda mejor que pongas las líneas temporales al revés, es decir lo más nuevo arriba, porque es lo que más impacta (y en general la experiencia va de menos a mas importante).

![image](https://user-images.githubusercontent.com/18369529/128673117-88ff6759-3cb1-4dd5-be9d-83449aeedc2d.png)

Suerte!

**Comment by luelvira** [comment]
Muchas gracias por el consejo! La verdad que tenía mis dudas sobre como ordenar los elementos.
